<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Atlas.Messaging.Outbox</RootNamespace>
    <AssemblyName>Atlas.Messaging.Outbox</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.SharedKernel\Atlas.SharedKernel.csproj" />
  </ItemGroup>

</Project>
