<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Atlas.Caching.Redis</RootNamespace>
    <AssemblyName>Atlas.Caching.Redis</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atlas.MultiTenancy\Atlas.MultiTenancy.csproj" />
  </ItemGroup>

</Project>
